export const TECH_STACK = [
  { name: 'Python', category: 'Language', level: 92, desc: 'ML, data processing, automation' },
  { name: 'SQL', category: 'Database', level: 88, desc: 'Complex querying & database optimization' },
  { name: 'Looker Studio', category: 'BI / Viz', level: 80, desc: 'Google business intelligence and dashboard reporting' },
  { name: 'Excel', category: 'Tool', level: 80, desc: 'Advanced functions & pivots' },
  { name: 'Tableau', category: 'BI / Viz', level: 85, desc: 'Interactive visual dashboards' },
  { name: 'PowerBI', category: 'BI / Viz', level: 82, desc: 'Corporate reporting & modeling' },
  { name: 'Next.js', category: 'Framework', level: 78, desc: 'Server-side rendering & applications' },
  { name: 'Supabase', category: 'Backend', level: 80, desc: 'PostgreSQL, Storage, and Auth' },
  { name: 'Git', category: 'DevOps', level: 85, desc: 'Version control & collaboration' },
  { name: 'Scikit-Learn', category: 'ML / AI', level: 90, desc: 'Classical predictive models' },
  { name: 'TensorFlow', category: 'ML / AI', level: 72, desc: 'Neural network construction' },
  { name: 'PyTorch', category: 'ML / AI', level: 78, desc: 'Deep learning research & modeling' },
  { name: 'SQL Server', category: 'Database', level: 84, desc: 'Enterprise relational database systems' },
  { name: 'SSIS', category: 'Tool', level: 80, desc: 'ETL & data integration workflows' },
  { name: 'Figma', category: 'Tool', level: 82, desc: 'Collaborative UI/UX design & prototyping' },
  { name: 'Canva', category: 'Tool', level: 85, desc: 'Graphic design & visual asset creation' },
  { name: 'Big Query', category: 'Database', level: 86, desc: 'Serverless cloud data warehouse' },
]
